import { useEffect, useRef, useState } from "react";
import { Bell, X } from "lucide-react";
import type { AlertItem } from "../../../shared/types";
import { api } from "../../services/api";
import { useApp } from "../../context/AppContext";
import { RISK_META } from "../../utils/risk";

export function AlertsBell() {
  const { settings } = useApp();
  const [open, setOpen] = useState(false);
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fetchedFor, setFetchedFor] = useState<string | null>(null);
  const locIdRef = useRef(settings.locationId);

  useEffect(() => {
    if (locIdRef.current === settings.locationId) return;
    locIdRef.current = settings.locationId;
    setAlerts([]);
    setFetchedFor(null);
    setError(null);
    setLoading(false);
  }, [settings.locationId]);

  useEffect(() => {
    if (!open || fetchedFor === settings.locationId || !settings.alertsEnabled) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    api
      .getAlerts(settings.locationId)
      .then((res) => {
        if (cancelled) return;
        setAlerts(res.alerts);
        setFetchedFor(settings.locationId);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Failed to load alerts");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, fetchedFor, settings.locationId, settings.alertsEnabled]);

  if (!settings.alertsEnabled) return null;

  const visible = alerts.filter((a) =>
    settings.alertMinSeverity === "moderate"
      ? true
      : settings.alertMinSeverity === "severe"
        ? a.severity === "severe"
        : a.severity === "high" || a.severity === "severe",
  );

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={`Alerts (${visible.length} active)`}
        aria-expanded={open}
        className="relative inline-flex items-center justify-center w-8 h-8 rounded-md text-[#666666] hover:bg-black/5 transition-colors"
      >
        <Bell className="w-4 h-4" aria-hidden />
        {visible.length > 0 ? (
          <span className="absolute -top-1 -right-1 min-w-4 h-4 px-1 rounded-full bg-[#E5484D] text-white text-[9px] font-bold flex items-center justify-center shadow-sm">
            {visible.length}
          </span>
        ) : null}
      </button>
      {open ? (
        <div className="absolute right-0 mt-2 w-80 max-w-[calc(100vw-2rem)] bg-white border border-[#EAEAEA] rounded-xl shadow-[0_8px_30px_rgb(0,0,0,0.08)] z-40 overflow-hidden">
          <div className="flex items-center justify-between px-4 py-3 border-b border-[#F0F0F0] bg-[#FAFAFA]/50">
            <h2 className="text-xs font-semibold tracking-tight text-[#111111]">Environmental Alerts</h2>
            <button
              type="button"
              onClick={() => setOpen(false)}
              aria-label="Close alerts"
              className="text-[#888888] hover:text-[#111111] transition-colors"
            >
              <X className="w-4 h-4" aria-hidden />
            </button>
          </div>
          <div className="max-h-80 overflow-y-auto p-2 space-y-1.5">
            {loading ? <p className="text-xs text-[#666666] p-2 text-center">Loading alerts…</p> : null}
            {error ? <p className="text-xs text-[#E5484D] p-2 text-center">{error}</p> : null}
            {!loading && !error && visible.length === 0 ? (
              <p className="text-xs text-[#888888] p-4 text-center">
                No alerts at or above your selected severity for this location.
              </p>
            ) : null}
            {visible.map((alert) => {
              const meta = RISK_META[alert.severity];
              return (
                <div key={alert.id} className={`rounded-lg p-3 ${meta.pillClass} shadow-sm border`}>
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs font-semibold text-[#111111]">{alert.title}</p>
                    <span className="text-[10px] font-medium tracking-wide uppercase">{meta.label}</span>
                  </div>
                  <p className="mt-1.5 text-[11px] leading-relaxed text-[#444444]">{alert.message}</p>
                </div>
              );
            })}
          </div>
          <div className="px-4 py-2 border-t border-[#F0F0F0] bg-[#FAFAFA] text-[10px] text-[#888888]">
            Generated by EcoGuard AI
          </div>
        </div>
      ) : null}
    </div>
  );
}
