import { useEffect, useRef, useState } from "react";
import { Bell, X } from "lucide-react";
import type { AlertItem } from "../../../shared/types";
import { api } from "../../services/api";
import { useApp } from "../../context/AppContext";
import { RiskPill } from "../ui/RiskPill";

export function AlertsBell() {
  const { settings, location } = useApp();
  const [open, setOpen] = useState(false);
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fetchedFor, setFetchedFor] = useState<string | null>(null);
  const locIdRef = useRef(settings.locationId);

  useEffect(() => {
    if (locIdRef.current === settings.locationId) return;
    locIdRef.current = settings.locationId;
    setAlerts([]);
    setFetchedFor(null);
    setError(null);
    setLoading(false);
  }, [settings.locationId]);

  useEffect(() => {
    if (!open || fetchedFor === settings.locationId || !settings.alertsEnabled) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    api
      .getAlerts(settings.locationId)
      .then((res) => {
        if (cancelled) return;
        setAlerts(res.alerts);
        setFetchedFor(settings.locationId);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Failed to load alerts");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, fetchedFor, settings.locationId, settings.alertsEnabled]);

  if (!settings.alertsEnabled) return null;

  const visible = alerts.filter((a) =>
    settings.alertMinSeverity === "moderate"
      ? true
      : settings.alertMinSeverity === "severe"
        ? a.severity === "severe"
        : a.severity === "high" || a.severity === "severe",
  );

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={`Alerts (${visible.length} active)`}
        aria-expanded={open}
        className="relative inline-flex items-center justify-center w-9 h-9 rounded-lg text-ink-2 hover:bg-black/5 transition-colors"
      >
        <Bell className="w-4 h-4" aria-hidden />
        {visible.length > 0 ? (
          <span className="absolute top-1 right-1 min-w-4 h-4 px-1 rounded-full bg-danger text-white text-[9px] font-bold flex items-center justify-center shadow-sm">
            {visible.length}
          </span>
        ) : null}
      </button>
      {open ? (
        <div className="absolute right-0 mt-2 w-80 max-w-[calc(100vw-2rem)] bg-surface border border-line rounded-xl shadow-[0_12px_40px_-12px_rgba(26,29,26,0.18)] z-40 overflow-hidden fade-in">
          <div className="flex items-center justify-between px-4 py-3 border-b border-line-2">
            <div>
              <h2 className="text-[13px] font-semibold text-ink">Environmental alerts</h2>
              <p className="text-[11px] text-ink-3 mt-0.5">{location.name}</p>
            </div>
            <button
              type="button"
              onClick={() => setOpen(false)}
              aria-label="Close alerts"
              className="text-ink-3 hover:text-ink transition-colors p-1 rounded-md hover:bg-black/5"
            >
              <X className="w-4 h-4" aria-hidden />
            </button>
          </div>
          <div className="max-h-80 overflow-y-auto p-2 space-y-1.5">
            {loading ? (
              <p className="text-xs text-ink-3 p-3 text-center">Loading alerts…</p>
            ) : null}
            {error ? <p className="text-xs text-danger-2 p-3 text-center">{error}</p> : null}
            {!loading && !error && visible.length === 0 ? (
              <p className="text-xs text-ink-3 p-4 text-center leading-relaxed">
                No alerts at or above your selected severity for this location.
              </p>
            ) : null}
            {visible.map((alert) => (
              <div key={alert.id} className="rounded-lg border border-line p-3 bg-surface">
                <div className="flex items-start justify-between gap-2">
                  <p className="text-[13px] font-semibold text-ink leading-snug">{alert.title}</p>
                  <RiskPill level={alert.severity} size="sm" className="shrink-0" />
                </div>
                <p className="mt-1.5 text-xs leading-relaxed text-ink-2">{alert.message}</p>
                <p className="mt-1.5 text-[10px] text-ink-3">{alert.agentName}</p>
              </div>
            ))}
          </div>
          <div className="px-4 py-2 border-t border-line-2 bg-surface-2 text-[10px] text-ink-3">
            Generated by EcoGuard AI — screening guidance, not official warnings
          </div>
        </div>
      ) : null}
    </div>
  );
}
