import { useEffect, useRef, useState } from "react";
import { Bell, X } from "lucide-react";
import type { AlertItem } from "../../../shared/types";
import { api } from "../../services/api";
import { useApp } from "../../context/AppContext";
import { RISK_META } from "../../utils/risk";

export function AlertsBell() {
  const { settings } = useApp();
  const [open, setOpen] = useState(false);
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fetchedFor, setFetchedFor] = useState<string | null>(null);
  const locIdRef = useRef(settings.locationId);

  useEffect(() => {
    if (locIdRef.current === settings.locationId) return;
    locIdRef.current = settings.locationId;
    setAlerts([]);
    setFetchedFor(null);
    setError(null);
    setLoading(false);
  }, [settings.locationId]);

  useEffect(() => {
    if (!open || fetchedFor === settings.locationId || !settings.alertsEnabled) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    api
      .getAlerts(settings.locationId)
      .then((res) => {
        if (cancelled) return;
        setAlerts(res.alerts);
        setFetchedFor(settings.locationId);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Failed to load alerts");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, fetchedFor, settings.locationId, settings.alertsEnabled]);

  if (!settings.alertsEnabled) return null;

  const visible = alerts.filter((a) =>
    settings.alertMinSeverity === "moderate"
      ? true
      : settings.alertMinSeverity === "severe"
        ? a.severity === "severe"
        : a.severity === "high" || a.severity === "severe",
  );

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-label={`Alerts (${visible.length} active)`}
        aria-expanded={open}
        className="relative inline-flex items-center justify-center w-9 h-9 rounded-lg border border-slate-200 bg-white text-slate-600 hover:bg-slate-50"
      >
        <Bell className="w-4 h-4" aria-hidden />
        {visible.length > 0 ? (
          <span className="absolute -top-1 -right-1 min-w-4 h-4 px-1 rounded-full bg-orange-600 text-white text-[10px] font-semibold flex items-center justify-center">
            {visible.length}
          </span>
        ) : null}
      </button>
      {open ? (
        <div className="absolute right-0 mt-2 w-80 max-w-[calc(100vw-2rem)] bg-white border border-slate-200 rounded-xl shadow-lg z-40">
          <div className="flex items-center justify-between px-4 py-3 border-b border-slate-100">
            <h2 className="text-sm font-semibold text-slate-800">Environmental alerts</h2>
            <button
              type="button"
              onClick={() => setOpen(false)}
              aria-label="Close alerts"
              className="text-slate-400 hover:text-slate-600"
            >
              <X className="w-4 h-4" aria-hidden />
            </button>
          </div>
          <div className="max-h-80 overflow-y-auto p-3 space-y-2">
            {loading ? <p className="text-sm text-slate-500 p-1">Loading alerts…</p> : null}
            {error ? <p className="text-sm text-red-700 p-1">{error}</p> : null}
            {!loading && !error && visible.length === 0 ? (
              <p className="text-sm text-slate-500 p-1">
                No alerts at or above your selected severity for this location.
              </p>
            ) : null}
            {visible.map((alert) => {
              const meta = RISK_META[alert.severity];
              return (
                <div key={alert.id} className={`rounded-lg border p-3 ${meta.pillClass}`}>
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs font-semibold uppercase tracking-wide">{alert.title}</p>
                    <span className="text-[10px] font-medium">severity: {meta.label}</span>
                  </div>
                  <p className="mt-1 text-xs leading-relaxed text-slate-700">{alert.message}</p>
                </div>
              );
            })}
          </div>
          <div className="px-4 py-2 border-t border-slate-100 text-[11px] text-slate-500">
            Generated by EcoGuard agents — not an official government alert.
          </div>
        </div>
      ) : null}
    </div>
  );
}
